### ISSUE TITLE
SDK is returning 404 when trying to register call

### ISSUE THREAD

**Issue by ouwargui** [adam-team/retell-typescript-sdk#4]
I tried through Postman and it works fine, but when I try using the SDK, it throws an error with status 404.

Response body:
```
{
  ContentType: "text/html; charset=utf-8",
  StatusCode: 404,
  RawResponse: Response (152 bytes) {
    ok: false,
    url: "https://api.re-tell.ai/register-call",
    status: 404,
    statusText: "Not Found",
    headers: Headers {
      "content-type": "text/html; charset=utf-8",
      "content-length": "152",
      "connection": "keep-alive",
      "date": "Fri, 23 Feb 2024 04:41:54 GMT",
      "access-control-allow-origin": "*",
      "content-security-policy": "default-src 'none'",
      "x-content-type-options": "nosniff",
      "via": "1.1 1f469fdd9fb3833da82121857bc25aae.cloudfront.net (CloudFront)",
      "x-xss-protection": "1; mode=block",
      "x-frame-options": "SAMEORIGIN",
      "referrer-policy": "strict-origin-when-cross-origin",
      "strict-transport-security": "max-age=31536000",
      "x-powered-by": "Express",
      "x-cache": "Error from cloudfront",
      "x-amz-cf-pop": "GRU3-P3",
      "x-amz-cf-id": "95VdRFt5SsFRpojew1Vd1tRZWQ1JACA6OrFIxV0HYcgTFjO56Gscqg==",
    },
    redirected: false,
    bodyUsed: false,
    Blob (152 bytes)
  },
}
```

I've also tried to change the URL from `https://api.re-tell.ai` to `https://api.retellai.com` but no luck.

Here's a video where in the first part I send a request from postman straight to the API and on the second part I send a request from postman to my app on ngrok and the Retell SDK return 404.

https://github.com/adam-team/retell-typescript-sdk/assets/44242141/446617e6-1c79-4fc8-a1c1-b8825250f2f1

**Comment by weijia-yu** [comment]
@ouwargui We couldn't reproduce the issue at our end unfortunately. Which version of SDK are you using and can you share your code snippet?

**Comment by ouwargui** [comment]
We can actually simplify the snippet above with:

```
import { RetellClient } from "retell-sdk";
import { AudioEncoding, AudioWebsocketProtocol } from "retell-sdk/models/components";

const retellClient = new RetellClient({
  apiKey: process.env.RETELL_API_KEY,
});

const res = await retellClient.registerCall({
  agentId: 'c1f38399f876f7ed5beb1466f8cde7de',
  audioWebsocketProtocol: AudioWebsocketProtocol.Twilio,
  audioEncoding: AudioEncoding.Mulaw,
  sampleRate: 8000
});
```

Output:
```
❯ bun dev
$ bun --watch src/index.ts
 9 |         const statusCode = response.status;
10 |         let bodyString = "";
11 |         if (body.length > 0) {
12 |             bodyString = `\n${body}`;
13 |         }
14 |         super(`${message}: Status ${statusCode}${bodyString}`);
             ^
SDKError: Unexpected API response: Status 404
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /register-call</pre>
</body>
</html>

      at new SDKError (/home/guik/dev/personal/retell-demo/node_modules/retell-sdk/models/errors/sdkerror.js:14:9)
      at /home/guik/dev/personal/retell-demo/node_modules/retell-sdk/sdk/sdk.js:218:19
 9 |         const statusCode = response.status;
10 |         let bodyString = "";
11 |         if (body.length > 0) {
12 |             bodyString = `\n${body}`;
13 |         }
14 |         super(`${message}: Status ${statusCode}${bodyString}`);
             ^
SDKError: Unexpected API response: Status 404
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /register-call</pre>
</body>
</html>

      at new SDKError (/home/guik/dev/personal/retell-demo/node_modules/retell-sdk/models/errors/sdkerror.js:14:9)
      at /home/guik/dev/personal/retell-demo/node_modules/retell-sdk/sdk/sdk.js:218:19
```

**Comment by ouwargui** [comment]
@weijia-yu It's probably a problem with Bun, since it's working with NodeJS.

**Comment by weijia-yu** [comment]
It looks like Bun's issue, thus closing the ticket. You can implement using RestAPI in Bun too
